<a href="https://colab.research.google.com/github/pdesire-20/Lab6/blob/main/lab_gpa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Lab: GPA 🎓

In this lab, you'll explore the GPA dataset again to find out more about the courses at Illinois!

Fun fact: the dataset you're using in this lab is the same dataset that Professor Wade uses to make the GPA visualizations! :)  Check this out here if you haven't seen it already: [https://waf.cs.illinois.edu/discovery/grade_disparity_between_sections_at_uiuc/](https://waf.cs.illinois.edu/discovery/grade_disparity_between_sections_at_uiuc/)


A few tips to remember:

- **You are not alone on your journey in learning programming!**
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

<hr style="color: #DD3403;">

# Part 1: Exploring GPA

## Load the GPA Dataset

Before we begin exploring the GPA Dataset, we've got to load it in! The most recent version of the "GPA Dataset" (up to Spring 2023) is available here:
```
https://waf.cs.illinois.edu/discovery/gpa.csv
```

Use Python to load this dataset into a DataFrame called `df`:

In [15]:
import pandas as pd
df= pd.read_csv("https://waf.cs.illinois.edu/discovery/gpa.csv")
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C+,C,C-,D+,D,D-,F,W,Students,Primary Instructor
0,2023,Spring,2023-sp,AAS,100,Intro Asian American Studies,DIS,0,11,5,...,0,0,0,0,0,0,1,0,22,"Shin, Jeongsu"
1,2023,Spring,2023-sp,AAS,100,Intro Asian American Studies,DIS,0,17,2,...,0,0,0,0,0,0,0,1,23,"Shin, Jeongsu"
2,2023,Spring,2023-sp,AAS,100,Intro Asian American Studies,DIS,0,13,2,...,0,0,1,0,0,0,1,0,21,"Lee, Sabrina Y"
3,2023,Spring,2023-sp,AAS,200,U.S. Race and Empire,LCD,6,15,5,...,0,0,0,0,1,0,1,0,33,"Sawada, Emilia"
4,2023,Spring,2023-sp,AAS,215,US Citizenship Comparatively,LCD,16,12,2,...,0,0,0,0,0,0,0,0,33,"Kwon, Soo Ah"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69064,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,0,1,3,0,0,0,2,1,31,"Stepanov, Alexei G"
69065,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,28,"Unger, David"
69066,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,5,1,1,0,2,0,1,0,28,"Morgan, William T"
69067,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,3,3,2,0,0,1,1,0,21,"Ott-Monsivais, Stephanie"
69068,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,0,4,0,0,1,0,2,0,39,"Keane, Richard D"

### 🔬 Test Case Checkpoint 🔬

In [16]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(df) == 69069), "This is not the GPA dataset you're looking for."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 1.1: The "Average GPA" Column
Each row in the GPA Dataset represents a **course section** at Illinois. For our exploratory data analysis, we are going to need an additional `Average GPA` column.

To create this column, we need to compute the **weighted average GPA** for each course section by taking into account the **number of students** who received each letter grade.

Add this new `Average GPA` column to our DataFrame `df` by finding the **products** of the **weight** associated with each **letter grade** and the number of said **letter grade** earned in each course section, **summing these products**, and then **dividing** by the **number of students** in the course section.

Remember:
- The **weight** of letter grades are as follows: $[A+ = 4.0, A = 4.0, A- = 3.67, \ldots  D- = 0.67, F = 0]$. <br> You can find a full scale at: https://registrar.illinois.edu/courses-grades/explanation-of-grades/
- The `Students` column of our DataFrame contains the number of students in a course section
- You've done this in your Mastery Platform homework before, now you're doing it for real :)

In [23]:
df['Average GPA'] = (df['A+'] * 4.0 + df['A'] * 4.0 + df['A-'] * 3.67 + df['B+'] * 3.33 + df['B'] * 3.0 + df['B-'] * 2.67 + df['C+'] * 2.33 + df['C'] * 2.0 + df['C-'] * 1.67 + df['D+'] * 1.33 + df['D'] * 1.0 + df['D-'] * 0.67 + df['F'] * 0.0) / df['Students']
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Students,Primary Instructor,Average GPA
0,2023,Spring,2023-sp,AAS,100,Intro Asian American Studies,DIS,0,11,5,...,0,0,0,0,0,1,0,22,"Shin, Jeongsu",3.530909
1,2023,Spring,2023-sp,AAS,100,Intro Asian American Studies,DIS,0,17,2,...,0,0,0,0,0,0,1,23,"Shin, Jeongsu",3.797391
2,2023,Spring,2023-sp,AAS,100,Intro Asian American Studies,DIS,0,13,2,...,0,1,0,0,0,1,0,21,"Lee, Sabrina Y",3.476667
3,2023,Spring,2023-sp,AAS,200,U.S. Race and Empire,LCD,6,15,5,...,0,0,0,1,0,1,0,33,"Sawada, Emilia",3.606364
4,2023,Spring,2023-sp,AAS,215,US Citizenship Comparatively,LCD,16,12,2,...,0,0,0,0,0,0,0,33,"Kwon, Soo Ah",3.889091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69064,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,31,"Stepanov, Alexei G",3.183226
69065,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,28,"Unger, David",3.774643
69066,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,1,1,0,2,0,1,0,28,"Morgan, William T",2.595714
69067,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,3,2,0,0,1,1,0,21,"Ott-Monsivais, Stephanie",2.603333
69068,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,4,0,0,1,0,2,0,39,"Keane, Richard D",3.205641

### 🔬 Test Case Checkpoint 🔬

In [20]:
## == TEST CASES for Puzzle 1.1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error or output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert( len(df) == 69069  ), "You shouldn't be changing the length of `df` when computing Average GPA."
assert( "Average GPA" in df.columns), "Make sure your new column is named 'Average GPA'."
assert( math.isclose(df['Average GPA'].mean(), 3.3701121347989282)), "Your calculation of the Average GPA is incorrect."

## == SUCCESS MESSAGE ==
# You'll only see this message (With the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 1.2: The "Hardest" and "Easiest" Courses?
One way to judge a course's difficulty is to consider its **Average GPA**.

Using the `Average GPA` column and the two cells below, find:
- The **50** courses with the **lowest** `Average GPA`, storing in the DataFrame `df_hard`
- The **50** courses with the **highest** `Average GPA`, storing the DataFrame `df_easy`

In [26]:
df_hard = df.nsmallest(50, "Average GPA")
df_hard

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Students,Primary Instructor,Average GPA
6215,2022,Spring,2022-sp,GS,199,College Academic Success,LCD,1,0,0,...,2,0,2,1,2,12,0,26,"Walk, Aaron J",1.140385
24225,2018,Fall,2018-fa,LER,120,Contemporary Labor Problems,ONL,0,0,1,...,1,2,1,1,0,15,0,28,"Taylor, Don",1.142857
8220,2021,Fall,2021-fa,CLCV,100,Vocab Building-GRK & LAT Roots,ONL,2,0,3,...,1,0,1,2,3,20,0,40,"Augoustakis, Antonios",1.208750
36697,2016,Spring,2016-sp,LER,100,Introduction to Labor Studies,ONL,0,1,0,...,4,1,1,1,1,10,0,24,"Hawking, Carol J",1.319583
44510,2014,Fall,2014-fa,LER,120,Contemporary Labor Problems,ONL,0,4,0,...,4,1,0,1,0,15,1,30,"Hershfield, David",1.400000
9322,2021,Fall,2021-fa,LER,100,Introduction to Labor Studies,ONL,0,1,0,...,3,0,2,0,1,11,0,26,"Ashby, Steven",1.410385
46778,2014,Spring,2014-sp,LER,120,Contemporary Labor Problems,ONL,0,1,3,...,3,0,0,0,2,11,0,25,"Cohen, Margaret L",1.427600
49575,2013,Fall,2013-fa,MATH,2,Introductory Algebra,LCD,0,0,0,...,10,5,3,3,2,5,3,31,"Aydin-Mullen, Yelda",1.430645
46853,2014,Spring,2014-sp,MATH,220,Calculus,LBD,0,3,0,...,5,0,2,1,0,11,1,28,"Gilbert, Rebekah A",1.476071
21497,2019,Spring,2019-sp,LER,100,Introduction to Labor Studies,ONL,0,2,1,...,0,0,0,2,1,9,0,21,"Cohen, Margaret L",1.491905
34425,2016,Fall,2016-fa,LER,120,Contemporary Labor Problems,NaN,0,2,2,...,0,1,2,1,2,8,2,22,"Hershfield, David",1.515455
34693,2016,Fall,2016-fa,MCB,245,Human Anat & Physiol Lab I,NaN,0,0,0,...,3,4,1,2,0,6,1,23,"Swigart, James P",1.522174
44557,2014,Fall,2014-fa,LLS,296,Bilingual US Latina/o Culture,LCD,3,1,0,...,1,1,1,0,2,11,1,27,"Romero, Rolando J",1.568519
44721,2014,Fall,2014-fa,MCB,245,Human Anat & Physiol Lab I,LAB,0,0,1,...,1,3,5,1,1,5,0,25,"Swigart, James P",1.586800
31626,2017,Spring,2017-sp,LER,100,Introduction to Labor Studies,NaN,0,2,1,...,3,2,0,1,0,9,0,23,"Ashby, Steven",1.594783
25576,2018,Spring,2018-sp,CHEM,101,Introductory Chemistry,NaN,1,5,8,...,10,9,11,23,10,26,7,132,"Decoste, Donald J",1.598864
34421,2016,Fall,2016-fa,LER,100,Introduction to Labor Studies,NaN,0,2,1,...,3,2,0,1,1,10,0,27,"Stewart, Beverly L",1.605185
7467,2022,Summer,2022-su,SPAN,141,Intro to Spanish Grammar,ONL,0,1,0,...,2,2,2,1,3,5,0,22,"Castro Cantu, Sara E",1.606364
34424,2016,Fall,2016-fa,LER,110,Labor and Social Movements,NaN,0,4,2,...,2,1,0,1,4,8,0,25,"Ashby, Steven",1.614400
60045,2011,Spring,2011-sp,MATH,115,Preparation for Calculus,LCD,1,4,2,...,5,0,9,11,2,18,0,71,"Carty, Thomas E",1.619296
34684,2016,Fall,2016-fa,MCB,245,Human Anat & Physiol Lab I,NaN,0,0,1,...,1,3,3,4,1,4,2,25,"Swigart, James P",1.626800
59981,2011,Spring,2011-sp,LER,100,Introduction to Labor Studies,ONL,2,1,0,...,1,2,0,0,1,9,2,22,"Konopacki, Mike",1.636364
46373,2014,Spring,2014-sp,ENGL,274,Contemporary Classics,LCD,0,1,3,...,1,2,1,0,0,8,1,21,"Hutner, Gordon",1.651429
39488,2015,Fall,2015-fa,MATH,181,A Mathematical World,LCD,1,3,0,...,3,1,1,1,1,8,0,23,"Loeb, Sarah J",1.651739
24435,2018,Fall,2018-fa,MCB,245,Human Anat & Physiol Lab I,LAB,0,0,1,...,4,1,0,1,1,7,0,23,"Swigart, James P",1.652174
34689,2016,Fall,2016-fa,MCB,245,Human Anat & Physiol Lab I,NaN,0,0,1,...,3,1,1,1,3,6,0,26,"Swigart, James P",1.654231
12396,2021,Summer,2021-su,CHEM,102,General Chemistry I,ONL,2,3,4,...,10,4,7,10,13,13,1,85,"Marville, Kelly",1.655294
58393,2011,Fall,2011-fa,TAM,251,Introductory Solid Mechanics,LEC,1,0,4,...,23,3,6,23,9,11,0,102,"Starzewski, Martin O",1.657157
63601,2011,Summer,2011-su,TAM,251,Introductory Solid Mechanics,LEC,1,0,4,...,23,3,6,23,9,11,0,102,"Starzewski, Martin O",1.657157
44306,2014,Fall,2014-fa,IE,300,Analysis of Data,LEC,4,1,3,...,13,10,9,8,2,14,4,75,"Tursun, Umit D",1.662400
51883,2013,Spring,2013-sp,MATH,115,Preparation for Calculus,LCD,0,3,5,...,9,6,6,3,6,26,4,96,"Lansing, Jennifer L",1.663438
22334,2019,Summer,2019-su,CHEM,102,General Chemistry I,ONL,0,2,2,...,4,3,3,3,9,10,6,52,"Marville, Kelly",1.667115
57506,2011,Fall,2011-fa,LER,110,Labor and Social Movements,ONL,0,3,0,...,2,3,0,3,0,7,0,24,"Saute, Robert",1.680417
62714,2011,Summer,2011-su,LER,110,Labor and Social Movements,ONL,0,3,0,...,2,3,0,3,0,7,0,24,"Saute, Robert",1.680417
19476,2019,Fall,2019-fa,MCB,245,Human Anat & Physiol Lab I,LAB,0,0,1,...,3,1,1,1,2,6,1,24,"Swigart, James P",1.681250
31631,2017,Spring,2017-sp,LER,110,Labor and Social Movements,NaN,0,3,2,...,3,0,0,1,0,12,2,29,"Schiavone, Michael",1.701724
36701,2016,Spring,2016-sp,LER,110,Labor and Social Movements,ONL,0,1,4,...,2,0,0,1,1,9,0,25,"Ashby, Steven",1.707200
34690,2016,Fall,2016-fa,MCB,245,Human Anat & Physiol Lab I,NaN,1,0,0,...,3,4,1,1,3,3,0,24,"Swigart, James P",1.708750
7466,2022,Summer,2022-su,SPAN,130,Intermediate Spanish,ONL,0,1,0,...,3,2,2,1,2,5,0,23,"Strocchia, Ilaria",1.710435
34423,2016,Fall,2016-fa,LER,110,Labor and Social Movements,NaN,0,2,2,...,1,3,0,0,0,11,2,29,"Schiavone, Michael",1.713103
44070,2014,Fall,2014-fa,FIN,300,Financial Markets,LCD,0,0,1,...,3,4,2,1,0,8,0,32,"Waspi, Kevin G",1.719063
46755,2014,Spring,2014-sp,LER,100,Introduction to Labor Studies,ONL,0,1,1,...,1,1,2,1,3,6,0,25,"Hertenstein, Edward",1.733600
11124,2021,Spring,2021-sp,ECON,302,Inter Microeconomic Theory,OD,2,1,0,...,3,2,0,2,1,8,0,28,"Kim, Sarah J",1.749643
45451,2014,Spring,2014-sp,ACE,100,Agr Cons and Resource Econ,DIS,0,0,1,...,2,2,1,1,5,2,0,23,"Gundersen, Lisa C",1.754348
6521,2022,Spring,2022-sp,LER,100,Introduction to Labor Studies,ONL,0,1,3,...,3,1,0,2,0,7,0,22,"Ashby, Steven",1.758182
9424,2021,Fall,2021-fa,MATH,124,Finite Mathematics,LCD,1,1,2,...,2,3,0,0,1,8,0,25,"Dao, Quang N",1.760800
52098,2013,Spring,2013-sp,MCB,354,Biochem & Phys Basis of Life,DIS,0,0,0,...,3,3,1,3,1,2,0,21,"Stenger, Alejandra L",1.777619
5931,2022,Spring,2022-sp,ECON,203,Economic Statistics II,LAB,2,1,0,...,2,0,2,2,7,1,0,21,"Martinez Garcia, Humberto",1.778571
42766,2015,Summer,2015-su,SPAN,103,Intermediate Spanish,LCD,0,0,0,...,4,0,0,0,4,6,0,28,"Lugo, Monica E",1.785714
38923,2015,Fall,2015-fa,FIN,300,Financial Markets,LCD,0,1,0,...,2,0,2,1,0,9,1,30,"Waspi, Kevin G",1.788667

In [27]:
df_easy = df.nlargest(50, "Average GPA")
df_easy

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Students,Primary Instructor,Average GPA
22401,2019,Summer,2019-su,IS,532,Theory & Pract Data Cleaning,ONL,266,18,1,...,0,0,0,0,0,0,0,286,"Ludaescher, Bertram",3.995350
12466,2021,Summer,2021-su,IS,537,Theory & Prct of Data Cleaning,ONL,407,9,0,...,0,0,0,0,0,0,0,419,NaN,3.995203
4472,2022,Fall,2022-fa,MUSC,487,Marching Illini,PR,0,289,0,...,0,0,0,0,0,0,1,291,"Houser, Barry L",3.993127
35355,2016,Spring,2016-sp,ACCY,398,Practical Problems in Atg,ONL,139,1,0,...,0,0,0,0,0,0,0,141,"Nekrasz, Frank",3.992908
31268,2017,Spring,2017-sp,EPSY,490,Prep for Recruitment Counselor,NaN,69,14,0,...,0,0,0,0,0,0,0,84,"Brown, Dawn M",3.992024
44790,2014,Fall,2014-fa,ME,199,Automotive Design Projects,LBD,8,111,0,...,0,0,0,0,0,0,0,120,"Philpott, Michael L",3.991667
32858,2016,Fall,2016-fa,ANSC,103,Working With Farm Animals,NaN,0,79,0,...,0,0,0,0,0,0,0,80,"Cobb, Alan R",3.991625
37829,2015,Fall,2015-fa,ANSC,103,Working With Farm Animals,LEC,0,76,0,...,0,0,0,0,0,0,0,77,"Cobb, Alan R",3.991299
7279,2022,Spring,2022-sp,VCM,673,Companion Animal Rehab,LCD,69,2,0,...,0,0,0,0,0,0,0,72,"Knap, Kimberly E",3.990694
54859,2012,Fall,2012-fa,MUS,273,Marching Illini,PR,0,308,0,...,0,0,0,0,0,0,0,311,"Houser, Barry L",3.990354
49177,2013,Fall,2013-fa,GS,101,Exploring General Studies,LCD,0,66,0,...,0,0,0,0,0,0,0,67,"Armstrong, Christopher M",3.990000
344,2023,Spring,2023-sp,BADM,324,Purchasing and Supply Mgmnt,LCD,61,4,0,...,0,0,0,0,0,0,0,66,"Cockrell, Adam L",3.989848
6383,2022,Spring,2022-sp,IS,534,Information Consulting,LCD,0,65,0,...,0,0,0,0,0,0,0,66,"Song, Yoo-Seong",3.989848
18775,2019,Fall,2019-fa,FIN,447,Real Estate Development,LCD,11,53,0,...,0,0,0,0,0,0,0,65,"Cannaday, Roger E",3.989692
4729,2022,Fall,2022-fa,SBC,512,Professional SBC Capstone Proj,ONL,54,8,0,...,0,0,0,0,0,0,0,63,"Clifton, Dionne J",3.989365
2245,2023,Summer,2023-su,MUS,133,Introduction to World Music,ONL,80,13,0,...,0,0,0,0,0,0,0,94,"Silvers, Michael B",3.989362
30505,2017,Spring,2017-sp,BADM,566,Supply Chain Management,NaN,32,25,0,...,0,0,0,0,0,0,0,58,"Mukherjee, Ujjal K",3.988448
1773,2023,Spring,2023-sp,MUSC,484,Concert Band,PR,0,82,0,...,0,0,0,0,0,0,0,83,"Rudy, Hannah L",3.987952
460,2023,Spring,2023-sp,BUS,201,Business Dynamics,LCD,15,39,0,...,0,0,0,0,0,0,0,55,"Luckman, Elizabeth",3.987818
29061,2017,Fall,2017-fa,IB,199,Undergraduate Open Seminar,NaN,0,81,0,...,0,0,0,0,0,0,1,82,"Arias Chauca, Lily C",3.987805
8712,2021,Fall,2021-fa,EPOL,500,Proseminar in EPOL,ONL,0,80,0,...,0,0,0,0,0,0,0,81,"Lee, Sharon S",3.987654
13642,2020,Fall,2020-fa,EPSY,408,Learning & Hum Dev w/ EdTech,ONL,69,10,1,...,0,0,0,0,0,0,0,81,"Cope, William",3.987654
26188,2018,Spring,2018-sp,EPSY,490,Prep for Recruitment Counselor,NaN,43,37,0,...,0,0,0,0,0,0,0,81,"Brown, Dawn M",3.987654
30206,2017,Spring,2017-sp,ACCY,398,Practical Problems in Atg,NaN,123,6,1,...,0,0,0,0,0,0,0,132,"Nekrasz, Frank",3.987348
9669,2021,Fall,2021-fa,MUSC,480,Wind Symphony,PR,0,51,0,...,0,0,0,0,0,0,0,52,"Peterson, Stephen",3.987115
45244,2014,Fall,2014-fa,SPED,405,Gen Educator's Role in SPED,LCD,40,10,0,...,0,0,0,0,0,0,0,51,"Taylor, Gregory G",3.986863
9504,2021,Fall,2021-fa,MBA,564,Applying Data Analytics Mrktg,ONL,0,680,0,...,0,0,0,0,0,2,1,683,"Yun, Joseph T",3.986823
10989,2021,Spring,2021-sp,DANC,100,Intro to Contemporary Dance,ONL,39,10,0,...,0,0,0,0,0,0,0,50,"Sapozhnikov, Anna",3.986600
13004,2020,Fall,2020-fa,BADM,567,Process Management,ONL,45,4,0,...,0,0,0,0,0,0,0,50,"Cockrell, Adam L",3.986600
15151,2020,Spring,2020-sp,ANSC,103,Working With Farm Animals,LEC,0,73,0,...,0,0,0,0,0,0,0,74,"Emmert, Jason L",3.986486
20685,2019,Spring,2019-sp,CI,473,Disciplinary Literacy,LEC,0,94,2,...,0,0,0,0,0,0,0,97,"Filkins, Scott R",3.986289
12308,2021,Spring,2021-sp,TE,360,Lect in Engrg Entrepreneurship,OLC,47,0,0,...,0,0,0,0,0,0,0,48,"Harbourt, Christopher M",3.986042
50910,2013,Spring,2013-sp,CHLH,380,Orientation to Internship,LCD,0,117,0,...,0,0,0,0,0,0,0,119,"Farner, Susan M",3.985966
11236,2021,Spring,2021-sp,EPS,533,Global Youth and Citizenship,ONL,4,42,0,...,0,0,0,0,0,0,0,47,"Herrera, Linda",3.985745
31953,2017,Spring,2017-sp,MUS,274,Basketball Band,NaN,0,138,0,...,1,0,0,0,0,0,0,139,"Houser, Barry L",3.985612
17107,2020,Summer,2020-su,EPSY,408,Learning & Hum Dev w/ EdTech,ONL,79,31,3,...,0,0,0,0,0,0,2,114,"Cope, William",3.985439
17332,2020,Winter,2020-wi,EPSY,408,Learning & Hum Dev w/ EdTech,ONL,79,31,3,...,0,0,0,0,0,0,2,114,"Cope, William",3.985439
23624,2018,Fall,2018-fa,EDUC,101,Education Orientation Seminar,LCD,0,67,0,...,0,0,0,0,0,0,1,68,"Jo, Katherine K",3.985294
31949,2017,Spring,2017-sp,MUS,250,Illini Strings,NaN,0,67,0,...,0,0,0,0,0,0,0,68,"May, Cameron L",3.985294
39769,2015,Fall,2015-fa,MUS,262,Women's Glee Club,PR,11,56,0,...,0,0,0,0,0,0,0,68,"Solya, Andrea",3.985294
5461,2022,Spring,2022-sp,BUS,301,Business in Action,LCD,0,44,0,...,0,0,0,0,0,0,0,45,"Kim, Heejin",3.985111
60299,2011,Spring,2011-sp,MSE,183,Freshman Materials Laboratory,LBD,0,66,0,...,0,0,0,0,0,0,0,67,"Braun, Paul V",3.985075
11532,2021,Spring,2021-sp,IS,507,"Data, Stat, Info",ONL,38,5,0,...,0,0,0,0,0,0,0,44,"Besser, Stephanie A",3.984773
1774,2023,Spring,2023-sp,MUSC,484,Concert Band,PR,0,64,0,...,0,0,0,0,0,0,0,65,"Brinberg, Isaac H",3.984615
33013,2016,Fall,2016-fa,BADM,420,Advanced Marketing Management,NaN,0,64,0,...,0,0,0,0,0,0,0,65,"Wolters, Mark E",3.984615
5333,2022,Spring,2022-sp,BADM,324,Purchasing and Supply Mgmnt,LCD,49,13,1,...,0,0,0,0,0,0,0,64,"Cockrell, Adam L",3.984375
43162,2014,Fall,2014-fa,BADM,261,Technology & Mgmt Seminar,LCD,0,62,0,...,0,0,0,0,0,0,0,63,"Quarton, John E",3.984127
50935,2013,Spring,2013-sp,CI,473,Literacy in Content Areas,LEC,37,23,1,...,0,0,0,0,0,0,0,62,"Dressman, Mark A",3.983871
13648,2020,Fall,2020-fa,EPSY,559,Advanced Learning Technologies,ONL,30,10,0,...,0,0,0,0,0,0,0,41,"Kalantzis, Mary",3.983659
19765,2019,Fall,2019-fa,PSYC,506,Statistical Methods I,LEC,16,24,0,...,0,0,0,0,0,0,0,41,"Gratton, Gabriele",3.983659

Now, using your two new DataFrames (`df_hard` and `df_easy`), find:
- The **mean course number** of the 50 hardest courses by GPA, storing in the variable `hard_avg`
- The **mean course number** of the 50 easiest courses by GPA, storing in the variable `easy_avg`

The **course number** of a course is stored in the **'Number'** column of our DataFrames.

In [28]:
hard_avg = df_hard["Number"].mean()
hard_avg

166.42

In [ ]:
easy_avg = df_hard["Number"].mean()
easy_avg

### 🔬 Test Case Checkpoint 🔬

In [ ]:
## == TEST CASE for Puzzle 1.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error or output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell(s), make changes, and RE-RUN your code and then this cell.
import math
assert( len(df_hard) == len(df_easy) == 50 ), "Your df_hard and df_easy should be picking the 50 courses with the lowest / highest average GPA respectively. Please double check that you are selecting 50 courses."
assert( math.isclose(df_hard['Average GPA'].sum(), 80.30481775738464) ), "Your df_hard is calculated incorrectly. Make sure you are finding the 50 courses with the lowest Average GPA."
assert( math.isclose(df_easy['Average GPA'].sum(), 199.38547959954138) ), "Your df_easy is calculated incorrectly. Make sure you are finding the 50 courses with the highest Average GPA."
assert( math.isclose(hard_avg, 166.42) ), "Your calculation for the average course number of 'hard' courses is incorrect. Make sure you are finding the mean of course numbers of df_hard."
assert( math.isclose(easy_avg, 372.74) or math.isclose(easy_avg, 375.56)), "Your calculation for the average course number of 'easy' courses is incorrect. Make sure you are finding the mean of course numbers of df_easy."

## == SUCCESS MESSAGE ==
# You'll only see this message (With the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

### Analysis: "Hardest" and "Easiest" Courses?

**Q1: After solving Puzzle 1.2, your friend has the following claim:**

> *"We know that the undergraduate courses are coded from 001 to 499, where a larger number (in the hundreds place) usually implies more advanced material.  Based on our results in the previous puzzles, the data shows that the junior-level and senior-level courses are clearly not the hardest courses at UIUC."*

**Comment on your friend's claim below. Do you think they are correct? Explain why or why not in at least three complete sentences.**

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

<hr style="color: #DD3403;">

# Part 2: GPA By Subject
We've explored some of the GPA Dataset as a whole, but what if we want to investigate **differences in GPA by subject**?

### Puzzle 2.1: Grouping by Subject
To look into the different Average GPAs for each Subject, we need to **group** our DataFrame.

In the following cell, create a new DataFrame, `df_subject`, which will contain this grouped GPA data. Using `df.groupby()`, **group** our original DataFrame (`df`) by `Subject` so each **letter grade column** contains the **total number of students** receiving the same grade in that `Subject`.

**NUMERIC ONLY**: For the agg function in the lab, we want to aggregate only the numeric columns:
- To do this, when you use `.agg("...")`, include the option `numeric_only=True`.
- For example, to aggregate by `sum`, you would use: `.agg("sum", numeric_only=True)`.
- Instead, to aggregate by `count`, you would use: `.agg("count", numeric_only=True)`.

**DO I USE `count` or `sum`?**:
- Each row in `df` represents a **course section** of a `Subject` with the **number of students** receiving grades for that course.
- Do you want to "count" the number of rows, or "sum" the number of students receiving each grade?
- And, don't forget to `.reset_index()`. :)

In [ ]:
df_subject = ...
df_subject

### 🔬 Test Case Checkpoint 🔬

In [ ]:
## == TEST CASE for Puzzle 2.1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error or output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell(s), make changes, and RE-RUN your code and then this cell.
import math
assert( 'df_subject' in vars() ), "Make sure your DataFrame grouped by 'Subject' is named 'df_subject'."
assert( len(df_subject) == 172 ), "Make sure you are grouping by 'Subject'. There are 172 Subjects in our original `df`, so the length of `df_subject` should be 172."
assert( math.isclose(df_subject.Students.mean(), 23723.837209302324) ), "Double-check that you are aggregating your df_subject correctly."

## == SUCCESS MESSAGE ==
# You'll only see this message (With the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

### Puzzle 2.2: Fixing our `Average GPA` Column
Your intuition may tell you that some columns in `df_subject` look off. This is correct - given the way we've grouped the data to find **total student counts** by grade, the `Year` and `Average GPA` columns are incorrect.

Let's fix this by redefining the `Average GPA` column in our `df_subject`.

The `Average GPA` column should contain the **weighted average GPA** of each `Subject` by taking into account the **number of students** who received each letter grade in said `Subject`.

Remember:
- The **weight** of letter grades are as follows: $[A+ = 4.0, A = 4.0, A- = 3.67, \ldots  D- = 0.67, F = 0]$. <br> You can find a full scale at: https://registrar.illinois.edu/courses-grades/explanation-of-grades/
- The `Students` column of our DataFrame contains the number of students in a `Subject`
- This Puzzle is **strikingly similar** to **Puzzle 1.1** in this lab - just make sure you use `df_subject` this time!

In [ ]:
df_subject['Average GPA'] = ...
df_subject

### 🔬 Test Case Checkpoint 🔬

In [ ]:
## == TEST CASES for Puzzle 2.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error or output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert( len(df_subject) == 172 ), "You shouldn't be changing the length of `df_subject` when recomputing Average GPA."
assert( "Average GPA" in df_subject.columns), "Make sure your column is still named 'Average GPA'."
assert( math.isclose(df_subject['Average GPA'].mean(), 3.4643567698520825) ), "Your calculation of the Average GPA by Subject is incorrect."

## == SUCCESS MESSAGE ==
# You'll only see this message (With the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

### Puzzle 2.3: The "Hardest" and "Easiest" Subjects?
One way we can judge a Subject's difficulty is to consider its **Average GPA**.

Using your `df_subject`'s  `Average GPA` column and the two cells below, find:
- The **10** Subjects with the **lowest** `Average GPA`, storing in the DataFrame `hard_subjects`
- The **10** Subjects with the **highest** `Average GPA`, storing the DataFrame `easy_subjects`

In [ ]:
hard_subjects = ...
hard_subjects

In [ ]:
easy_subjects = ...
easy_subjects

### 🔬 Test Case Checkpoint 🔬

In [ ]:
## == TEST CASES for Puzzle 2.3 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error or output, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert( len(hard_subjects) == len(easy_subjects) == 10 ), "Make sure you are selecting the ten hardest or easiest subjects by GPA. This means your hard_subjects and easy_subjects DataFrames should both have exactly ten rows."
assert( math.isclose(hard_subjects['Average GPA'].sum(), 29.72180057281505) ), "Your calculation for the hardest subjects by GPA is incorrect. Remember, here harder = lower Average GPA."
assert( math.isclose(easy_subjects['Average GPA'].sum(), 38.47633638756495) ), "Your calculation for the easiest subjects by GPA is incorrect. Remember, here easier = higher Average GPA."

## == SUCCESS MESSAGE ==
# You'll only see this message (With the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

### Analysis: "Hardest" and "Easiest" Subjects?

**Q2: Observe the `Subject` column of the `hard_subjects` and `easy_subjects` you've found in Puzzle 2.3 above. Do you think these are truly the "Hardest" and "Easiest" subjects at Illinois? Explain why or why not.**


*Note: You can use http://catalog.illinois.edu/courses-of-instruction/ to find what the different `Subject` codes mean.*

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

### Puzzle 2.4: Visualizing GPA by Subject
We've got the **Average GPA** of each `Subject` at Illinois, but what if we want to look at the **bigger picture** across all subjects? Well, data visualization comes to the rescue!

Generate a **histogram** of the **Average GPA** in your `df_subject`:

In [ ]:
...

### Analysis: Histogram Interpretations

**Q3: Based on the histogram you generated above, what do you think the Average GPA across all courses in a typical Subject at Illinois is? No need for an exact answer, just estimate.**

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

### Puzzle 2.5: Your Major!
We've done a lot of analysis on every course and every subject, but Data Science should also be personal to you!

Using your `df_subject`, isolate the row containing the `Subject` of **your Major**, storing in the variable `my_subject`:

(If you're undecided, you can pick any `Subject`!)

In [ ]:
my_subject = ...
my_subject

### Analysis: Your Major's Average GPA

**Q4: Observe the `Average GPA` column of your subject from Puzzle 2.5 above. Is it higher or lower than you expected?**

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

<hr style="color: #DD3403;">

# Part 3: GPA By Year
At this point, we've investigated the GPA Dataset as a whole and grouped by `Subject`. While our GPA Dataset contains **a lot** of course data, some of the listed courses are quite old: **dating back to 2010**! To put that into perspective, a senior in college now would be no more than **10 years old** in 2010.

One can question the changes to GPA **over time**. Some questions may include:
- Has GPA gone up, because classes became "easier"?
- Has the GPA fallen because of stricter grading policies?
- How was GPA impacted in 2019-2020 at the brunt of COVID?

You will gain some insight into the answers to questions in this section of the lab.

### Puzzle 3.1: Grouping by Year
To look into how the GPA changes by `Year`, we need to again **group** our DataFrame.

In the following cell, create a new DataFrame, `df_year`, which will contain this grouped GPA data. Using `df.groupby()`, **group** our original DataFrame (`df`) by `Year` so each **letter grade column** contains the **total number of students** receiving said grade in that `Year`.

Remember: You did something quite similar in Puzzle 2.1 to create `df_subject`. This might help you decide what type of **aggregation** (`.agg()`) to use when **grouping**.
- In this puzzle, you should also use `numeric_only=True` in your `agg` function, just like in Puzzle 2.1.
- And, don't forget to `.reset_index()`! :)

In [ ]:
df_year = ...
df_year

### 🔬 Test Case Checkpoint 🔬

In [ ]:
## == TEST CASE for Puzzle 3.1 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert( 'df_year' in vars() ), "Make sure your DataFrame grouped by Year is named 'df_year'."
assert( len(df_year) == 14 ), "Make sure you are grouping by 'Year'. There are 14 years in our original `df`, so the length of `df_years` should be 14."
assert( math.isclose(df_year.Students.mean(), 291464.28571428574) ), "Double-check that you are aggregating your df_year correctly."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

### Puzzle 3.2: Fixing our `Average GPA` Column Again
Some columns in `df_year` are incorrectly calculated given the way we've grouped the data.

Let's fix this by redefining the `Average GPA` column in our `df_year`.

The `Average GPA` column should contain the **weighted average GPA** of each `Year` by taking into account the **number of students** who received each letter grade in said `Year`.

Remember: You've done this twice before in **Puzzle 1.1** and **Puzzle 2.2** - just make sure you use `df_year` this time!

In [ ]:
...

### 🔬 Test Case Checkpoint 🔬

In [ ]:
## == TEST CASE for Puzzle 3.2 ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert( len(df_year) == 14 ), "You shouldn't be changing the length of `df_year` when recomputing Average GPA."
assert( "Average GPA" in df_year.columns), "Make sure your column is still named 'Average GPA'."
assert( math.isclose(df_year['Average GPA'].mean(), 3.3272744718333738) ), "Your calculation of the Average GPA by Year is incorrect."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

### Puzzle 3.3: Visualizing GPA over Time
We now have the data of the `Average GPA` across the University over time in years. Using this data, we can generate yet another visualization built-in to Pandas to visualize this data: a **line plot**!

You can plot a **connected line** that draws your **numeric data** from a DataFrame, `df`, using the syntax:

&emsp;`df.plot.line(x='column1', y='column2')`

This line of code plots the line and specifies the **column names** to be used for the **x-values** and **y-values** of the points on your line plot.


In the cell below, using similar syntax, plot the **average GPA over time** using `df_year`.

*Hint: the `Year` column should provide **x-values** and the `Average GPA` column should provide **y-values**.*

In [ ]:
...

***Side Note***: If you're using **dark mode**, you may not be able to see the **axes** and **axes labels** of the graph.

**Only if** this is the case, please **copy and run** the following **two lines** of code in a cell:

---
```py
from matplotlib import style
style.use('dark_background')
```
---

And then **re-run your plotting code** above.

### Analysis: Plotted GPA over Time

**Q5: Note a few observations you have about the changes to `Average GPA` at Illinois over time. Is there an overall trend? What events could have spiked increases to the Average GPA? Respond with at least three sentences.**

*(✏️ Edit this cell to replace this text with your answer. ✏️)*

<hr style="color: #DD3403;">